<?php

use Illuminate\Database\Seeder;

class IndustryTypesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $industriesArray = array(
            array('type' => "Accounting",),
            array('type' => "Airlines / Aviation",),
            array('type' => "Alternative Dispute Resolution",),
            array('type' => "Alternative Medicine",),
            array('type' => "Animation",),
            array('type' => "Apparel / Fashion",),
            array('type' => "Architecture / Planning",),
            array('type' => "Arts / Crafts",),
            array('type' => "Automotive",),
            array('type' => "Aviation / Aerospace",),
            array('type' => "Banking / Mortgage",),
            array('type' => "Biotechnology / Greentech",),
            array('type' => "Broadcast Media",),
            array('type' => "Building Materials",),
            array('type' => "Business Supplies / Equipment",),
            array('type' => "Capital Markets / Hedge Fund / Private Equity",),
            array('type' => "Chemicals",),
            array('type' => "Civic / Social Organization",),
            array('type' => "Civil Engineering",),
            array('type' => "Commercial Real Estate",),
            array('type' => "Computer Games",),
            array('type' => "Computer Hardware",),
            array('type' => "Computer Networking",),
            array('type' => "Computer Software / Engineering",),
            array('type' => "Computer / Network Security",),
            array('type' => "Construction",),
            array('type' => "Consumer Electronics",),
            array('type' => "Consumer Goods",),
            array('type' => "Consumer Services",),
            array('type' => "Cosmetics",),
            array('type' => "Dairy",),
            array('type' => "Defense / Space",),
            array('type' => "Design",),
            array('type' => "E - Learning",),
            array('type' => "Education Management",),
            array('type' => "Electrical / Electronic Manufacturing",),
            array('type' => "Entertainment / Movie Production",),
            array('type' => "Environmental Services",),
            array('type' => "Events Services",),
            array('type' => "Executive Office",),
            array('type' => "Facilities Services",),
            array('type' => "Farming",),
            array('type' => "Financial Services",),
            array('type' => "Fine Art",),
            array('type' => "Fishery",),
            array('type' => "Food Production",),
            array('type' => "Food / Beverages",),
            array('type' => "Fundraising",),
            array('type' => "Furniture",),
            array('type' => "Gambling / Casinos",),
            array('type' => "Glass / Ceramics / Concrete",),
            array('type' => "Government Administration",),
            array('type' => "Government Relations",),
            array('type' => "Graphic Design / Web Design",),
            array('type' => "Health / Fitness",),
            array('type' => "Higher Education / Acadamia",),
            array('type' => "Hospital / Health Care",),
            array('type' => "Hospitality",),
            array('type' => "Human Resources / HR",),
            array('type' => "Import / Export",),
            array('type' => "Individual / Family Services",),
            array('type' => "Industrial Automation",),
            array('type' => "Information Services",),
            array('type' => "Information Technology / IT",),
            array('type' => "Insurance",),
            array('type' => "International Affairs",),
            array('type' => "International Trade / Development",),
            array('type' => "Internet",),
            array('type' => "Investment Banking / Venture",),
            array('type' => "Investment Management / Hedge Fund / Private Equity",),
            array('type' => "Judiciary",),
            array('type' => "Law Enforcement",),
            array('type' => "Law Practice / Law Firms",),
            array('type' => "Legal Services",),
            array('type' => "Legislative Office",),
            array('type' => "Leisure / Travel",),
            array('type' => "Library",),
            array('type' => "Logistics / Procurement",),
            array('type' => "Luxury Goods / Jewelry",),
            array('type' => "Machinery",),
            array('type' => "Management Consulting",),
            array('type' => "Maritime",),
            array('type' => "Market Research",),
            array('type' => "Marketing / Advertising / Sales",),
            array('type' => "Mechanical or Industrial Engineering",),
            array('type' => "Media Production",),
            array('type' => "Medical Equipment",),
            array('type' => "Medical Practice",),
            array('type' => "Mental Health Care",),
            array('type' => "Military Industry",),
            array('type' => "Mining / Metals",),
            array('type' => "Motion Pictures / Film",),
            array('type' => "Museums / Institutions",),
            array('type' => "Music",),
            array('type' => "Nanotechnology",),
            array('type' => "Newspapers / Journalism",),
            array('type' => "Non - Profit / Volunteering",),
            array('type' => "Oil / Energy / Solar / Greentech",),
            array('type' => "Online Publishing",),
            array('type' => "Others",),
            array('type' => "Outsourcing / Offshoring",),
            array('type' => "Package / Freight Delivery",),
            array('type' => "Packaging / Containers",),
            array('type' => "Paper / Forest Products",),
            array('type' => "Performing Arts",),
            array('type' => "Pharmaceuticals",),
            array('type' => "Philanthropy",),
            array('type' => "Photography",),
            array('type' => "Plastics",),
            array('type' => "Political Organization",),
            array('type' => "Primary / Secondary Education",),
            array('type' => "Printing",),
            array('type' => "Professional Training",),
            array('type' => "Program Development",),
            array('type' => "Public Relations / PR",),
            array('type' => "Public Safety",),
            array('type' => "Publishing Industry",),
            array('type' => "Railroad Manufacture",),
            array('type' => "Ranching",),
            array('type' => "Real Estate / Mortgage",),
            array('type' => "Recreational Facilities / Services",),
            array('type' => "Religious Institutions",),
            array('type' => "Renewables / Environment",),
            array('type' => "Research Industry",),
            array('type' => "Restaurants",),
            array('type' => "Retail Industry",),
            array('type' => "Security / Investigations",),
            array('type' => "Semiconductors",),
            array('type' => "Shipbuilding",),
            array('type' => "Sporting Goods",),
            array('type' => "Sports",),
            array('type' => "Staffing / Recruiting",),
            array('type' => "Supermarkets",),
            array('type' => "Telecommunications",),
            array('type' => "Textiles",),
            array('type' => "Think Tanks",),
            array('type' => "Tobacco",),
            array('type' => "Translation / Localization",),
            array('type' => "Transportation",),
            array('type' => "Utilities",),
            array('type' => "Venture Capital / VC",),
            array('type' => "Veterinary",),
            array('type' => "Warehousing",),
            array('type' => "Wholesale",),
            array('type' => "Wine / Spirits",),
            array('type' => "Wireless",),
            array('type' => "Writing / Editing")

        );
        DB::table('industry_types')->insert($industriesArray);
    }
}
