<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Organisation extends Model
{
    /*Needed to make all attributes mass assignable*/
    protected $guarded = [];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::created(function ($org) {
            OrganisationConfig::create([
                'organisation_id'=>$org->id,
            ]);
        }
        );
    }

    public function users()
    {
        return $this->hasMany(User::class);
    }

    public function visitors()
    {
        return $this->belongsToMany(Visitor::class);
    }
    public function subscriptions(){
        return $this->hasMany(Subscription::class);
    }
    public function organisation_config()
    {
        return $this->hasOne(OrganisationConfig::class);
    }

}
