<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Visitor extends Model
{
    protected $dates = [
        'updated_at',
        'created_at',
        'deleted_at',
        'transaction_date',
    ];
    /*Needed to make all attributes mass assignable*/
    protected $guarded = [];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::created(function ($visitor) {
            /* Appointment::create(
                 [
                     'organisation_id' => 1,
                     'visitor_id' => 1,
                     'department_visited' => 'ne',
                     'comments' => 'mje'
                 ]
             );*/
        });
    }

    public function appointments()
    {

        return $this->hasMany(Appointment::class);
    }

    public function organisations()
    {

        return $this->belongsToMany(Organisation::class);
    }

    public function scopeFilterDates($query)
    {
        $date = explode(" - ", request()->input('from-to', ""));

        if (count($date) != 2) {
            $date = [now()->subDays(29)->format("Y-m-d"), now()->addDays(29)->format("Y-m-d")];
        }

        return $query->whereBetween('date_of_visit', $date);
    }

    public function assets()
    {

        return $this->hasMany(Asset::class);
    }

}